# Generated by Django 5.2 on 2025-04-16 12:08
from django.contrib.auth.hashers import make_password
from django.db import migrations

def create_dummy_user(apps, schema_editor):
    User = apps.get_model('users', 'User')

    if not User.objects.filter(username='dummy').exists():
        User.objects.create(
            username='dummy',
            email='dummy@example.com',
            password=make_password('dummy123'),
            is_staff=False,
            is_superuser=False,
            coins=0,
        )

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_scheduledreward_is_processed"),
    ]

    operations = [
        migrations.RunPython(create_dummy_user),
    ]